#!/usr/bin/env python3
"""Checks for theta-parameter separation and modular-convention bookkeeping."""
import cmath
import itertools
import math

# Heat-trace exponent identity:
# exp(-s n^2/R^2) = exp(pi i tau_J n^2), tau_J=i s/(pi R^2).
s=0.73
R=1.41
tauJ=1j*s/(math.pi*R*R)
for n in range(-5,6):
    lhs=cmath.exp(-s*n*n/(R*R))
    rhs=cmath.exp(math.pi*1j*tauJ*n*n)
    assert abs(lhs-rhs)<1e-14

# T^2 invariance is termwise exact for exp(pi i n^2 tau).
for n in range(-10,11):
    assert abs(cmath.exp(math.pi*1j*n*n*2)-1)<1e-12

# T is not invariance: n=1 gets a minus sign.
assert abs(cmath.exp(math.pi*1j)+1)<1e-12

# Compute |SL(2,F2)| = 6 and the subgroup generated by S mod 2 has order 2.
mats=[]
for a,b,c,d in itertools.product(range(2),repeat=4):
    if (a*d-b*c)%2==1:
        mats.append((a,b,c,d))
assert len(mats)==6

I2=(1,0,0,1)
S=(0,1,1,0)  # -1 == 1 mod 2
theta_image={I2,S}
assert len(theta_image)==2
assert len(mats)//len(theta_image)==3

# Dimension warning is documentary; this checker verifies the exact algebraic
# heat-map and subgroup-index claims.
print("PASS: heat parameter maps to dimensionless tau_J; T^2 is exact, T is not, and Gamma_theta has index 3 mod 2")
